

name: COSIMA-CI 
 
on:
  workflow_dispatch:

jobs:
  
  
  run_Figs14-20-23-24-PlotWOCETransects.yml:
    name: Figs14-20-23-24-PlotWOCETransects.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Figs14-20-23-24-PlotWOCETransects.yml
    secrets: inherit

  
  run_Fig4-DrakePassageTransport.yml:
    name: Fig4-DrakePassageTransport.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Fig4-DrakePassageTransport.yml
    secrets: inherit

  
  run_Fig12-ZonalTempSaltBias.yml:
    name: Fig12-ZonalTempSaltBias.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Fig12-ZonalTempSaltBias.yml
    secrets: inherit

  
  run_Fig3-GlobalTimeseries.yml:
    name: Fig3-GlobalTimeseries.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Fig3-GlobalTimeseries.yml
    secrets: inherit

  
  run_Hovmoller_Temperature_Depth.yml:
    name: Hovmoller_Temperature_Depth.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Hovmoller_Temperature_Depth.yml
    secrets: inherit

  
  run_Dask_Distributed.yml:
    name: Dask_Distributed.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Dask_Distributed.yml
    secrets: inherit

  
  run_Ice_Diagnostics.yml:
    name: Ice_Diagnostics.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Ice_Diagnostics.yml
    secrets: inherit

  
  run_Global_Ocean_Volumetric_Temperature_and_Salinity_Change.yml:
    name: Global_Ocean_Volumetric_Temperature_and_Salinity_Change.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Global_Ocean_Volumetric_Temperature_and_Salinity_Change.yml
    secrets: inherit

  
  run_Cross-slope_section_potrho_cc.yml:
    name: Cross-slope_section_potrho_cc.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Cross-slope_section_potrho_cc.yml
    secrets: inherit

  
  run_Barotropic_Streamfunction_model_agnostic.yml:
    name: Barotropic_Streamfunction_model_agnostic.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Barotropic_Streamfunction_model_agnostic.yml
    secrets: inherit

  
  run_Querying_Scalar_Quantities_and_Annually_Averaged_Timeseries.yml:
    name: Querying_Scalar_Quantities_and_Annually_Averaged_Timeseries.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Querying_Scalar_Quantities_and_Annually_Averaged_Timeseries.yml
    secrets: inherit

  
  run_Transport_Through_Straits.yml:
    name: Transport_Through_Straits.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Transport_Through_Straits.yml
    secrets: inherit

  
  run_Cross-slope_section.yml:
    name: Cross-slope_section.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Cross-slope_section.yml
    secrets: inherit

  
  run_Age_at_the_Bottom.yml:
    name: Age_at_the_Bottom.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Age_at_the_Bottom.yml
    secrets: inherit

  
  run_Surface_Water_Mass_Transformation.yml:
    name: Surface_Water_Mass_Transformation.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Surface_Water_Mass_Transformation.yml
    secrets: inherit

  
  run_Geostrophic_Velocities_from_Sea_Level.yml:
    name: Geostrophic_Velocities_from_Sea_Level.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Geostrophic_Velocities_from_Sea_Level.yml
    secrets: inherit

  
  run_Binning_transformation_from_depth_to_potential_density.yml:
    name: Binning_transformation_from_depth_to_potential_density.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Binning_transformation_from_depth_to_potential_density.yml
    secrets: inherit

  
  run_Equatorial_thermal_and_zonal_velocity_structure.yml:
    name: Equatorial_thermal_and_zonal_velocity_structure.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Equatorial_thermal_and_zonal_velocity_structure.yml
    secrets: inherit

  
  run_TemperatureSalinityDiagrams_mom5_mom6.yml:
    name: TemperatureSalinityDiagrams_mom5_mom6.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: TemperatureSalinityDiagrams_mom5_mom6.yml
    secrets: inherit

  
  run_Decomposing_kinetic_energy_into_mean_and_transient.yml:
    name: Decomposing_kinetic_energy_into_mean_and_transient.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Decomposing_kinetic_energy_into_mean_and_transient.yml
    secrets: inherit

  
  run_NearestNeighbourDistance.yml:
    name: NearestNeighbourDistance.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: NearestNeighbourDistance.yml
    secrets: inherit

  
  run_Model_Resolution_Comparison.yml:
    name: Model_Resolution_Comparison.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Model_Resolution_Comparison.yml
    secrets: inherit

  
  run_Particle_tracking_with_Parcels.yml:
    name: Particle_tracking_with_Parcels.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Particle_tracking_with_Parcels.yml
    secrets: inherit

  
  run_SeaIceSeasonality_DFA.yml:
    name: SeaIceSeasonality_DFA.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: SeaIceSeasonality_DFA.yml
    secrets: inherit

  
  run_True_Zonal_Mean.yml:
    name: True_Zonal_Mean.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: True_Zonal_Mean.yml
    secrets: inherit

  
  run_Regridding.yml:
    name: Regridding.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Regridding.yml
    secrets: inherit

  
  run_Bathymetry.yml:
    name: Bathymetry.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Bathymetry.yml
    secrets: inherit

  
  run_RelativeVorticity.yml:
    name: RelativeVorticity.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: RelativeVorticity.yml
    secrets: inherit

  
  run_Cross-contour_transport.yml:
    name: Cross-contour_transport.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Cross-contour_transport.yml
    secrets: inherit

  
  run_Compare_SSH_model_obs.yml:
    name: Compare_SSH_model_obs.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Compare_SSH_model_obs.yml
    secrets: inherit

  
  run_Compare_SST_SSS_TemperatureSalinity_to_WOA13.yml:
    name: Compare_SST_SSS_TemperatureSalinity_to_WOA13.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Compare_SST_SSS_TemperatureSalinity_to_WOA13.yml
    secrets: inherit

  
  run_Zonally_Averaged_Global_Meridional_Overturning_Circulation.yml:
    name: Zonally_Averaged_Global_Meridional_Overturning_Circulation.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Zonally_Averaged_Global_Meridional_Overturning_Circulation.yml
    secrets: inherit

  
  run_Meridional_heat_transport.yml:
    name: Meridional_heat_transport.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Meridional_heat_transport.yml
    secrets: inherit

  
  run_Atlantic_IndoPacific_Basin_Overturning_Circulation.yml:
    name: Atlantic_IndoPacific_Basin_Overturning_Circulation.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Atlantic_IndoPacific_Basin_Overturning_Circulation.yml
    secrets: inherit

  
  run_SeaIce_Plot_Example.yml:
    name: SeaIce_Plot_Example.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: SeaIce_Plot_Example.yml
    secrets: inherit

  
  run_Using_Explorer_tools.yml:
    name: Using_Explorer_tools.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Using_Explorer_tools.yml
    secrets: inherit

  
  run_COSIMA_CookBook_Tutorial.yml:
    name: COSIMA_CookBook_Tutorial.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: COSIMA_CookBook_Tutorial.yml
    secrets: inherit

  
  run_Model_Agnostic_Analysis.yml:
    name: Model_Agnostic_Analysis.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Model_Agnostic_Analysis.yml
    secrets: inherit

  
  run_Making_Maps_with_Cartopy.yml:
    name: Making_Maps_with_Cartopy.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Making_Maps_with_Cartopy.yml
    secrets: inherit

  
  run_Make_Your_Own_Database.yml:
    name: Make_Your_Own_Database.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Make_Your_Own_Database.yml
    secrets: inherit

  
  run_Spatial_selection.yml:
    name: Spatial_selection.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Spatial_selection.yml
    secrets: inherit

  
  run_Template_For_Notebooks.yml:
    name: Template_For_Notebooks.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Template_For_Notebooks.yml
    secrets: inherit

  
  run_Submitting_analysis_jobs_to_gadi.yml:
    name: Submitting_analysis_jobs_to_gadi.yml
    uses: ACCESS-NRI/COSIMA-recipes-workflow/.github/workflows/run_recipe.yml@main
    with:
      recipe-name: Submitting_analysis_jobs_to_gadi.yml
    secrets: inherit

  