name: COSIMA Single Recipe Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cosima-recipe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run COSIMA Recipe on Gadi
        id: cosima
        uses: rbeucher/smart-recipe-runner@main
        with:
          recipe_type: 'cosima'
          recipe_name: 'Barotropic_Streamfunction.ipynb'
          repository_url: 'https://github.com/COSIMA/cosima-recipes'
          gadi_username: ${{ secrets.GADI_USERNAME }}
          gadi_ssh_key: ${{ secrets.GADI_SSH_KEY }}
          gadi_ssh_passphrase: ${{ secrets.GADI_SSH_PASSPHRASE }}
          scripts_dir: ${{ secrets.GADI_SCRIPTS_DIR }}
          project: 'tm70'
      
      - name: Monitor Job
        run: |
          echo "COSIMA job submitted!"
          echo "Job ID: ${{ steps.cosima.outputs.job_id }}"
          echo "Monitor with: qstat ${{ steps.cosima.outputs.job_id }}"
